### ISSUE TITLE
Support onOpen and onClose

### ISSUE THREAD

**Issue by dgoemans** [Faslet/widget_react_component#1]
window._faslet global supports the following methods:
```
      onOpen?: (productId?: string) => unknown
      onClose?: (productId?: string) => unknown
```
and the react component should also have these configurable as props

**Comment by dgoemans** [comment]
cc @fedwar
This has been resolve in this release
https://github.com/Faslet/widget_react_component/releases/tag/v0.4.0

**Comment by Fedwar** [comment]
@dgoemans , I am very grateful to you and appreciate your work and time! Thank you for your efforts and for finding the time for me.
